# Start with the Rocky Linux 8 base image
FROM --platform=linux/amd64 rockylinux/rockylinux:8.8

# Install Python, OpenSSH, and other utilities
RUN dnf -y install python3 python3-pip openssh-server openssh-clients && \
    dnf clean all && \
    pip3 install --upgrade pip && \
    pip3 install ansible

# Set up SSHD
RUN ssh-keygen -A
RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && \
    echo "root:root" | chpasswd

# Ensure Python and Pip are set to the right version
RUN alternatives --set python /usr/bin/python3

# Expose the SSH port
EXPOSE 22
EXPOSE 8080

# Start SSHD in the foreground
CMD ["/usr/sbin/sshd", "-D"]
